### ISSUE TITLE
More recent Python version than 3.6.9 on Ubuntu 18.04

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/cpython#26]
https://web.archive.org/web/20230128071941/https://packages.ubuntu.com/bionic/python3 - 3.6.5 the computation IPOL server has 3.6.9

https://www.python.org/downloads/release/python-3123/ (source: https://www.python.org/downloads/)

https://www.python.org/ftp/python/3.12.3/Python-3.12.3.tar.xz (source: https://www.python.org/downloads/)

```bash
wget 'https://www.python.org/ftp/python/3.12.3/Python-3.12.3.tar.xz'
tar -xf Python-3.12.3.tar.xz
cd Python-3.12.3/
./configure
```

```bash
make
```
```
The necessary bits to build these optional modules were not found:
_bz2                  _dbm                  _gdbm              
_hashlib              _ssl                  _tkinter           
To find the necessary bits, look in configure.ac and config.log.

Could not build the ssl module!
Python requires a OpenSSL 1.1.1 or newer

Checked 111 modules (31 built-in, 73 shared, 1 n/a on linux-x86_64, 0 disabled, 6 missing, 0 failed on import)
```

For an approach like [Benjamin_Loison/apt/issues/6](https://salsa.debian.org/Benjamin_Loison/apt/-/issues/6):

`download_package.py`:
```python
#!/usr/bin/python3

import requests
from lxml import html
import time

PACKAGE = 'python3'
UBUNTU_VERSION = 'jammy'
ARCHITECTURE = 'amd64'

def getTree(url):
    url = f'https://packages.ubuntu.com/{UBUNTU_VERSION}/{url}'
    print(f'Requesting {url}...')
    response = requests.get(url)
    if response.status_code == 500:
        print('Received HTTP error 500!')
        time.sleep(1)
        return getTree(url)
    text = response.text
    #print(f'{response.status_code=}')
    #print(f'{text=}')
    print('Response received!')
    tree = html.fromstring(text)
    if tree.xpath('//title')[0].text_content() == 'Ubuntu – Error':
        print('Title mentioned an error!')
        time.sleep(1)
        return getTree(url)
    return tree

packagesAlreadyDownloaded = set()

def downloadPackage(package):
    if package in packagesAlreadyDownloaded:
        return
    #print(f'{package=}')
    packagesAlreadyDownloaded.add(package)
    
    url = f'{ARCHITECTURE}/{package}/download'
    tree = getTree(url)
    packageName = tree.xpath('//kbd')[0].text_content()
    #print(f'{packageName=}')
    directory = tree.xpath('//tt')[0].text_content()
    #print(f'{directory=}')
    #return
    downloadUrl = f'http://security.ubuntu.com/ubuntu/{directory}{packageName}'
    print(f'Checking {downloadUrl}')
    assert requests.head(downloadUrl).status_code == 200
    #downloadUrl = tree.xpath('//a[text()="security.ubuntu.com/ubuntu"]')[0].attrib['href']
    print(f'{downloadUrl=}')
    
    dependencies = getTree(package).xpath('//ul[@class="uldep"]/li/dl/dt/a')
    for dependency in dependencies:
        #print(f'{dependency.text_content()=}')
        downloadPackage(dependency.text_content())

downloadPackage(PACKAGE)
```

```bash
./download_package.py | grep downloadUrl | cut -d "'" -f2 > urls_of_debs.txt
wget -i urls_of_debs.txt
```

```bash
./usr/bin/python3
```
```
./usr/bin/python3: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./usr/bin/python3)
./usr/bin/python3: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./usr/bin/python3)
./usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./usr/bin/python3)
./usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./usr/bin/python3)
./usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./usr/bin/python3)
./usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./usr/bin/python3)
```

No matter `LD_LIBRARY_PATH` change.

**Comment by Benjamin-Loison** [comment]
Would help [Robust_image_source_identification_on_modern_smartphones/issues/82](https://gitea.lemnoslife.com/Benjamin_Loison/Robust_image_source_identification_on_modern_smartphones/issues/82).

**Comment by Benjamin-Loison** [comment]
I have been told to try conda and miniconda to manage my own Python version. Both commands return `command not found` currently.

**Comment by Benjamin-Loison** [comment]
It indeed solved this issue.

**Comment by Benjamin-Loison** [comment]
Trying to use `rawpy` on nix:

https://search.nixos.org/packages does not return any entry contrarily to `scikit-image` (`python312Packages.scikit-image`).

```bash
pip install numpy
```
```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 328, in run
    session = self.get_default_session(options)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 72, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 84, in _build_session
    index_urls=self._get_index_urls(options),
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/network/session.py", line 240, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/network/session.py", line 133, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py", line 122, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py", line 677, in linux_distribution
    self.version(),
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py", line 737, in version
    self.lsb_release_attr('release'),
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py", line 899, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py", line 552, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py", line 1012, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/main.py", line 47, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 103, in main
    return self._main(args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 191, in _main
    self.handle_pip_version_check(options)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 139, in handle_pip_version_check
    timeout=min(5, options.timeout)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 84, in _build_session
    index_urls=self._get_index_urls(options),
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/network/session.py", line 240, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/network/session.py", line 133, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py", line 122, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py", line 677, in linux_distribution
    self.version(),
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py", line 737, in version
    self.lsb_release_attr('release'),
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py", line 899, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py", line 552, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/distro.py", line 1012, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
```

```bash
python3 -m venv .venv
```

`test.py`:
```python
import numpy
```

```bash
.venv/bin/python3 test.py
```
```
Traceback (most recent call last):
  File "/home/bloison/test.py", line 3, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

```bash
.venv/bin/pip install numpy
```
```
Collecting numpy
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Installing collected packages: numpy
Successfully installed numpy-1.26.4
```

```bash
.venv/bin/python3 test.py
```
```
Traceback (most recent call last):
  File "/home/bloison/.venv/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/bloison/.venv/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/bloison/.venv/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libz.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bloison/.venv/lib/python3.11/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/home/bloison/.venv/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/home/bloison/.venv/lib/python3.11/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/home/bloison/.venv/bin/python3"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libz.so.1: cannot open shared object file: No such file or directory


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bloison/test.py", line 3, in <module>
    import numpy
  File "/home/bloison/.venv/lib/python3.11/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

[fix-python](https://github.com/GuillaumeDesforges/fix-python) solves this issue for `numpy`.

Source: https://wiki.nixos.org/w/index.php?title=Python&oldid=13058#On_NixOS

**Comment by Benjamin-Loison** [comment]
However, for `rawpy` I get:

```bash
.venv/bin/python -c 'import rawpy'
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bloison/.venv/lib/python3.11/site-packages/rawpy/__init__.py", line 5, in <module>
    import rawpy._rawpy
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
```

`.nix/libs.nix`:
```nix
let pkgs = import (builtins.getFlake "nixpkgs") { };
in [
  pkgs.gcc.cc
  pkgs.glibc
  pkgs.zlib
  pkgs.rawpy
]
```

```bash
./fix-python --venv .venv --libs .nix/libs.nix
```
[logs.txt](https://github.com/user-attachments/files/15645882/logs.txt)


does not help.

Maybe `pkgs.rawpy` is not appropriate.
`stdenv.cc.cc.lib` as proposed in [GuillaumeDesforges/fix-python/issues/9](https://github.com/GuillaumeDesforges/fix-python/issues/9) does not help.

Should check `logs.txt` for `libstdc++`.

I have not paid attention to `nix: command not found`, solving the `PATH` solves the issue for `rawpy`.

**Comment by Benjamin-Loison** [comment]
https://nix.dev/tutorials/first-steps/declarative-shell#startup-commands to avoid having to `activate` `venv` at each login.
