### ISSUE TITLE
`datetime` `strftime` in French while should be in English

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/cpython#61]
### Bug description:

```python
import datetime

print(datetime.datetime.now().strftime('%a %-d %b'))
```
```
mar. 24 déc.
```

### CPython versions tested on:

3.12

**Comment by Benjamin-Loison** [comment]
Related to #47.

**Comment by Benjamin-Loison** [comment]
```bash
locale
```
<details>
<summary>Output:</summary>

```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
</details>

**Comment by Benjamin-Loison** [comment]
Pyzo > *Python* > *Edit shell configurations...* > *startupScript* does not seem involved.

**Comment by Benjamin-Loison** [comment]
On my Linux Mint 22 Cinnamon Framework 13.

**Comment by Benjamin-Loison** [comment]
```python
import locale

locale.setlocale(locale.LC_ALL, 'en_EN.UTF-8')
```
<details>
<summary>Output:</summary>

```
Traceback (most recent call last):
  File "<console>", line 3, in <module>
  File "/usr/lib/python3.12/locale.py", line 615, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
</details>

```python
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
```

is a workaround.
