### ISSUE TITLE
Encode string to be compatible with `.vcf` `N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:`

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/cpython#62]
### Proposal:

```python
# Add a code block here, if required
```

### Has this already been discussed elsewhere?

No response given

**Comment by Benjamin-Loison** [comment]
https://docs.python.org/3.13/library/quopri.html

```python
import quopri
```

```python
quopri.encodestring('test')
```
<details>
<summary>Output:</summary>

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3.12/quopri.py", line 105, in encodestring
    return b2a_qp(s, quotetabs=quotetabs, header=header)
TypeError: a bytes-like object is required, not 'str'
```
</details>

```python
quopri.encodestring(b'test')
```
```
b'test'
``

**Comment by Benjamin-Loison** [comment]
```python
import urllib.parse as ul

print(ul.unquote_plus('CENSORED'.replace('=', '%'))
```

works fine for decoding.

**Comment by Benjamin-Loison** [comment]
[Wikipedia: VCard](https://en.wikipedia.org/wiki/VCard)

**Comment by Benjamin-Loison** [comment]
For `.vcf` it does `=` encoding with LineageOS Contacts is not mandatory.
